// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_auth_app/test/helpers/test_mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_auth_app/core/core.dart' as _i6;
import 'package:flutter_auth_app/data/data.dart' as _i3;
import 'package:flutter_auth_app/domain/domain.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeRegisterResponse_1 extends _i1.Fake implements _i3.RegisterResponse {
}

class _FakeLoginResponse_2 extends _i1.Fake implements _i3.LoginResponse {}

class _FakeUsersResponse_3 extends _i1.Fake implements _i3.UsersResponse {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i4.Login>> login(
          _i4.LoginParams? loginParams) =>
      (super.noSuchMethod(Invocation.method(#login, [loginParams]),
              returnValue: Future<_i2.Either<_i6.Failure, _i4.Login>>.value(
                  _FakeEither_0<_i6.Failure, _i4.Login>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i4.Login>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i4.Register>> register(
          _i4.RegisterParams? registerParams) =>
      (super.noSuchMethod(Invocation.method(#register, [registerParams]),
              returnValue: Future<_i2.Either<_i6.Failure, _i4.Register>>.value(
                  _FakeEither_0<_i6.Failure, _i4.Register>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i4.Register>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i4.Users>> users(
          _i4.UsersParams? usersParams) =>
      (super.noSuchMethod(Invocation.method(#users, [usersParams]),
              returnValue: Future<_i2.Either<_i6.Failure, _i4.Users>>.value(
                  _FakeEither_0<_i6.Failure, _i4.Users>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i4.Users>>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i3.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.RegisterResponse> register(
          _i4.RegisterParams? registerParams) =>
      (super.noSuchMethod(Invocation.method(#register, [registerParams]),
              returnValue:
                  Future<_i3.RegisterResponse>.value(_FakeRegisterResponse_1()))
          as _i5.Future<_i3.RegisterResponse>);
  @override
  _i5.Future<_i3.LoginResponse> login(_i4.LoginParams? loginParams) =>
      (super.noSuchMethod(Invocation.method(#login, [loginParams]),
              returnValue:
                  Future<_i3.LoginResponse>.value(_FakeLoginResponse_2()))
          as _i5.Future<_i3.LoginResponse>);
  @override
  _i5.Future<_i3.UsersResponse> users(_i4.UsersParams? userParams) =>
      (super.noSuchMethod(Invocation.method(#users, [userParams]),
              returnValue:
                  Future<_i3.UsersResponse>.value(_FakeUsersResponse_3()))
          as _i5.Future<_i3.UsersResponse>);
}
