// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsPrd.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsPrd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsPrd have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPrd have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPrd have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPrd have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPrd are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdU1UveIWYwX-Lsmtl7pIigbu5lug-pTU',
    appId: '1:933342696488:android:2a6b2649b130a09e87511d',
    messagingSenderId: '933342696488',
    projectId: 'mobile-app-bd59b',
    storageBucket: 'mobile-app-bd59b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPG4_LhFSS94Jez8k20Mu4i7cyCn26hzc',
    appId: '1:933342696488:ios:3ddb617c88b0363187511d',
    messagingSenderId: '933342696488',
    projectId: 'mobile-app-bd59b',
    storageBucket: 'mobile-app-bd59b.appspot.com',
    androidClientId:
        '933342696488-i2co7br6pib2js7a8vsjpio4164n0qci.apps.googleusercontent.com',
    iosClientId:
        '933342696488-ekbqsc1q8pkvk61nj5p0f04061ivr0ug.apps.googleusercontent.com',
    iosBundleId: 'com.lazycatlabs.auths',
  );
}
