// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsStg.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsStg have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsStg have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsStg have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsStg have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsStg are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXDLxYlgYywHeVs8Ch8uOq2t2BmtjOM0s',
    appId: '1:520881115656:android:5ce1808f01692ab2fd77bd',
    messagingSenderId: '520881115656',
    projectId: 'sample-49e7c',
    storageBucket: 'sample-49e7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgylLbnzngRGnumT5dnyfx4foQ2Qdu3dY',
    appId: '1:520881115656:ios:49ddee0a3cacac0bfd77bd',
    messagingSenderId: '520881115656',
    projectId: 'sample-49e7c',
    storageBucket: 'sample-49e7c.appspot.com',
    androidClientId:
        '520881115656-a76c2vaojcsa2kj1qk243eclfna6j6ff.apps.googleusercontent.com',
    iosBundleId: 'com.lazycatlabs.auths.stg',
  );
}
